swagger: "2.0"

info:
  title: SendIT API
  description: SendIT is a courier service that helps users deliver parcels to different destinations.
  version: 1.0.0

host: localhost:3000
basePath: /api/v1

produces: application/json

paths:
  /:
    get:
      summary: Query base route
      responses:
        "200":
          description: "API base route"
  /auth/signup:
    post:
      summary: Signup a new user
      consumes: application/json
      parameters:
        - in: body
          name: user
          description: Signup details
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: User signed up successfully
          schema:
            $ref: "#/definitions/Auth_Success"
        "400":
          description: Invalid request
          schema:
            $ref: "#/definitions/Error"
        "409":
          description: Conflict creating new user
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/Error"
  /auth/login:
    post:
      summary: Login a user
      parameters:
        - in: body
          description: Login details
          name: login
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: User logged in successfully
          schema:
            $ref: "#/definitions/Auth_Success"
        "401":
          description: Authentication failed
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Auth_Success:
    type: object
    properties:
      status:
        type: integer
        example: 200
      data:
        type: array
        items:
          type: object
          properties:
            users:
              type: object
            token:
              type: string
  Error:
    type: object
    properties:
      status:
        type: integer
      error:
        type: string
  User:
    type: object
    properties:
      firstname:
        type: string
      lastname:
        type: string
      othernames:
        type: string
      email:
        type: string
      username:
        type: string
      password:
        type: string
      isAdmin:
        type: string
      phone:
        type: string
      required:
        - firstname
        - lastname
        - email
        - username
        - password
        - phone
  Login:
    type: object
    properties:
      userId:
        type: string
      password:
        type: string
