language: node_js

node_js:
  - 12

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    secure: c7NbwjfquvTM9HWjv+2Qmkcnb/eK6EGRwVErLNJTPrGhBDN5RKzky7Lz4zZ3hFARQ/MZvmPZ5/S7F9c53Yw+I4cjx0vkuiOwdRPazGquOAbbOaD2tH9IEcUXDf3aQ60ORZgVuOTckjkNWTIgzwE71Cwhqo0RHGNQSyztUyUU7J91IGLSWa8PONjITdD06GN53lCBlzGcknRLrSXu1IVRPL5BLoy9gcxQiuWZbmHuJkMfXdqtHLmFn5yMHr1CnDp48wAepNZfBjOhZbDyFQGChm9QREXZKaMO5n4ZIsgCPnUQGwXQAFehVVqyzf3rkQCrL8IFAd+VzNgg+UHM9rCoz/GLMIA6YYLjbic2x801lz+vYxwJ7IsYJFTYb6NpwrizAvLHkn86QkjqYLCJ9k5tq8eZHkJM/JHeQ9a8dD6LJc7upQABRmmeEclIrcLCfltVWCpYWVyuZFejC+Bi3lV9yibc1RLqCN3H5ik5Es+irfWe2Pe6Gyxxls1DipAJPfQAfaMa43/l/w2zeJYpyQMiq4BKcZr/17ZWax8Q03MgOQJePdKFevDKdGi+FNucJWZ34Ykj/fb1blAImqDFH1ROWnie6r+yyZ6ibqfcmO5YZq40l+G30or7GR2X6n4H4QM+smZLFD4VYmb94XBzj8VkVvbao5TQsdSuoYaKTfb6sPA=
