version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "Hello"

  say-world:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - run:
          name: Say World
          command: echo "World!"

  print-my-name:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Print name
          command: echo << MY_NAME >>

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world:
          requires:
            - say-hello
      - print-my-name
